### ISSUE TITLE
Lost hot reloading, maybe leak

### ISSUE THREAD

**Issue by snatvb** [Houtamelo/gdext_coroutines#2]
Hello, when I add code that connected with your library, godot can't reload extension. It seems like smt holds and doesn't give unload the library.

In file: `src\utils\coroutines.rs`
```rs
use gdext_coroutines::prelude::{wait_until, Yield};
use godot::{
    classes::Node,
    obj::{Gd, GodotClass},
};

pub fn wait_for_node<T: GodotClass>(
    node: &Gd<T>,
    mut f: impl FnMut(Gd<T>) -> bool + 'static,
) -> Yield {
    let mut node = node.clone();
    wait_until(move || f(node.to_owned()))
}
```

if comment `use gdext_coroutines::prelude::{wait_until, Yield};` and function body - reload works fine.
After uncomment godot holds the libarary infinitelly.

For text I comment and uncomment `#[export]` in `src\main_scene.rs`:
```rs
pub struct Main {
    #[export]
    mob_scene: Gd<PackedScene>,
```

**Tested platform**: Win 11(x86), MacOS(arm)

**Showcase**:
[showcase.zip](https://github.com/user-attachments/files/16715583/showcase.zip)

**Comment by Houtamelo** [comment]
It's bizarre that out of all things the culprit seems to be a pure rust function that isn't exposed to Godot. I'll see about reporting this to Gdext

**Comment by snatvb** [comment]
Yes, add this is enough to lost reload feature:
```rs
use std::ops::{Coroutine, CoroutineState};
```

**Comment by snatvb** [comment]
Interesting: https://github.com/godot-rust/gdext/issues/874#issuecomment-2334242065

**Comment by snatvb** [comment]
So, here is new information:

**rust/src/lib.rs**:
```rs
/*
 * Copyright (c) godot-rust; Bromeon and contributors.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#![feature(coroutines, coroutine_trait)]
#![allow(unused)]
use godot::prelude::*;

mod hud;
mod main_scene;
mod mob;
mod player;

struct DodgeTheCreeps;

#[gdextension]
unsafe impl ExtensionLibrary for DodgeTheCreeps {}
```

**rust/src/player.rs**
```rs
// use gdext_coroutines::prelude::{wait_until, Yield};
use godot::classes::{AnimatedSprite2D, Area2D, CollisionShape2D, IArea2D, PhysicsBody2D};
use godot::prelude::*;

#[derive(GodotClass)]
#[class(base=Area2D)]
pub struct Player {
    // #[export]
    speed: real,
    screen_size: Vector2,

    base: Base<Area2D>,
}
```

Cargo.toml:
```toml
[package]
name = "dodge-the-creeps"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
  "experimental-godot-api",
  "experimental-threads",
] }
rand = "0.8"
gdext_coroutines = { version = "0.4", features = ["temp_gdext_patch"] }

[patch.crates-io]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = [
  "experimental-godot-api",
  "experimental-threads",
] }
```

Uncomment `// use gdext_coroutines::prelude::{wait_until, Yield};` leads to error in enigne:
`core/extension/gdextension.cpp:508 - Extension marked as reloadable, but attempted to register class 'SpireCoroutine' which doesn't support reloading. Perhaps your language binding don't support it? Reloading disabled for this extension.`

[showcase.zip](https://github.com/user-attachments/files/16909787/showcase.zip)
