### ISSUE TITLE
GodotClass not implemented for SpireCoroutine

### ISSUE THREAD

**Issue by AdminCrystal** [Houtamelo/gdext_coroutines#6]
Honestly probably a skill issue on my part. Get this error
```rust
error[E0277]: Only classes registered with Godot are allowed in this context
  --> src\lib.rs:46:35
   |
46 |     fn test_routine(&mut self) -> Gd<SpireCoroutine> {
   |                                   ^^^^^^^^^^^^^^^^^^ the trait `godot::prelude::GodotClass` is not implemented for `SpireCoroutine`
   |
   = note: you can use `#[derive(GodotClass)]` to register your own structs with Godot
```

Cargo.toml
```toml
[package]
name = "rust_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" , features = ["experimental-threads"]}
gdext_coroutines = { version = "0.4.3", features = ["async"] }
mr_starter = {git = "https://gitlab.com/admincrystal/poc_monorepo.git", branch = "main", features = []}
sqlx = {version = "0.8.2", features = ["sqlite"]}
smol = { version = "2.0.2" }
async-compat = "0.2.4"
```

Code (I took it from integration tests, also tried with my own and no luck)
```rust
#![feature(coroutines)]
#![feature(coroutine_trait)]
#![feature(stmt_expr_attributes)]
#![feature(unboxed_closures)]

use std::cell::OnceCell;
use std::rc::Rc;
use std::sync::{Arc, OnceLock};
use gdext_coroutines::prelude::SpireCoroutine;
use godot::prelude::*;
use godot::classes::{Label, Node2D};
use godot::classes::INode2D;
use smol::{Executor, future, LocalExecutor};
use sqlx::{migrate, Pool, Sqlite, SqliteConnection, SqlitePool, Transaction};
use sqlx::Connection;
use mr_starter::anyhow::Result;

use std::time::Duration;
use gdext_coroutines::prelude::*;
use godot::classes::node::ProcessMode;
use godot::obj::WithBaseField;
use godot::prelude::*;

use async_compat::Compat;
use gdext_coroutines::prelude::*;
use godot::prelude::*;
use mr_starter::chrono::Local;
use smol::net::resolve;

#[derive(GodotClass)]
#[class(init, base = Node)]
struct TestClass {
    base: Base<Node>,
}


#[godot_api]
impl TestClass {
    #[func]
    fn test_routine(&mut self) -> Gd<SpireCoroutine> {
        self.start_async_task(Compat::new(
            async {
                godot_print!("Using compat layer!");
                smol::Timer::after(Duration::from_secs(2)).await;
                godot_print!("Awaited 2 seconds, returning 5");
                5_i32
            }))
    }

    #[func]
    fn test_from_other_node(node: Gd<Node>) -> Gd<SpireCoroutine> {
        node.start_async_task(Compat::new(
            async {
                godot_print!("Async task from other node!");
                smol::Timer::after(Duration::from_secs(2)).await;
                godot_print!("Awaited 2 seconds, returning `finished task`");
                "finished task"
            }))
    }
}

#[godot_api]
impl INode for TestClass {
    fn ready(&mut self) {
        let base = self.base().to_godot();
        test_1(base);
    }
}
```

**Comment by Houtamelo** [comment]
@AdminCrystal 

`gdext_coroutines` version `4.3` uses `godot-1.3` as a dependency, which is hosted on [crates.io](https://crates.io/crates/godot).

These lines in your "Cargo.toml" indicate that your project uses the latest version of gdext from github (not crates.io):
```toml
[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" , features = ["experimental-threads"]}
```

What's happening here is that the version of `gdext_coroutines` you're using implements traits from `godot-1.3` (the crate on crates.io), not the github version.

You can fix this by using the github version of `gdext_coroutines`, which also points to the github version of `godot`:
```toml
[dependencies]
gdext_coroutines = { package = "gdext_coroutines", git = "https://github.com/Houtamelo/gdext_coroutines", features = ["async"] }
```

That should fix your issue.
